"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { api } from "../../../lib/api";
import { RiskEvent, GraphData } from "../../../lib/types";
import RiskScoreRing from "../../../components/RiskScoreRing";
import ShapBarChart from "../../../components/ShapBarChart";
import TypewriterText from "../../../components/TypewriterText";
import GraphCanvas from "../../../components/GraphCanvas";
import { 
  ArrowLeft, 
  FileText, 
  ShieldAlert, 
  Database,
  Cpu, 
  Download,
  FileDown, 
  Layers 
} from "lucide-react";

export default function CaseDetail() {
  const params = useParams();
  const router = useRouter();
  const caseId = params.id as string;

  const [event, setEvent] = useState<RiskEvent | null>(null);
  const [subgraph, setSubgraph] = useState<GraphData | null>(null);
  const [selectedNode, setSelectedNode] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [graphLoading, setGraphLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadCaseData = async () => {
      try {
        setLoading(true);
        // 1. Fetch risk event directly (Fix 12)
        const found = await api.getEvent(caseId);

        if (!found) {
          setError(`Case with ID ${caseId} not found in database.`);
          setLoading(false);
          return;
        }

        setEvent(found);
        setLoading(false);

        // 2. Fetch 2-hop subgraph for the entity
        try {
          setGraphLoading(true);
          const targetId = found.customer_id || found.entity_id;
          const sub = await api.getSubgraph(targetId);
          setSubgraph(sub);
        } catch (subErr: any) {
          console.error("Subgraph load error:", subErr);
          // Don't fail the whole page, just show empty graph
        } finally {
          setGraphLoading(false);
        }
      } catch (err: any) {
        setError(err.message || "Failed to load forensic data");
        setLoading(false);
      }
    };

    if (caseId) loadCaseData();
  }, [caseId]);

  // Action download handler
  const downloadCaseReport = () => {
    const actionStr = typeof event.action === 'object' ? event.action.action : event.action;
    const actionLevelStr = typeof event.action === 'object' ? event.action.level : (event as any).action_level;
    const reportText = `
============================================================
           SETU IDENTITY SECURITY SYSTEM - CASE FILE
============================================================
Case ID: ${event.id}
Target Entity ID: ${event.entity_id}
Entity Type: ${event.entity_type}
Timestamp: ${event.timestamp}
Reviewed: ${event.reviewed ? "YES" : "NO"}
Review Outcome: ${event.review_outcome || "UNREVIEWED"}

--------------------- RISK EVALUATION ---------------------
Final GNN Threat Score: ${event.risk_score.toFixed(2)}%
Friction Policy Decision: ${actionStr} (Threat Level: ${actionLevelStr})

--------------------- AI COMPLIANCE ANALYSIS ---------------------
Generated By Model: ${event.model_id}
Explanation:
${event.explanation}

--------------------- SHAP NEURAL WEIGHTS ---------------------
${event.shap_attributions
  .map((attr) => `- ${attr.feature}: ${attr.contribution > 0 ? "+" : ""}${attr.contribution.toFixed(4)}`)
  .join("\n")}

============================================================
Generated on ${new Date().toLocaleString("en-IN")}
    `.trim();

    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `case_report_${event.entity_id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="flex h-screen w-full items-center justify-center bg-soc-bg text-soc-cyan">
        <div className="flex flex-col items-center gap-3">
          <span className="h-8 w-8 animate-spin rounded-full border-2 border-soc-cyan border-t-transparent"></span>
          <span className="font-mono text-xs uppercase tracking-widest animate-pulse">Decompressing Case File...</span>
        </div>
      </div>
    );
  }

  if (error || !event) {
    return (
      <div className="p-8 min-h-screen flex items-center justify-center">
        <div className="rounded-lg border border-soc-red bg-soc-surface p-6 max-w-md text-center">
          <ShieldAlert className="h-10 w-10 text-soc-red mx-auto mb-4" />
          <h2 className="font-display text-lg font-bold text-soc-textPrimary mb-2">Forensic Query Failure</h2>
          <p className="text-xs text-soc-textSecondary mb-6">{error || "Incident case could not be verified."}</p>
          <button
            onClick={() => router.push("/dashboard")}
            className="rounded border border-soc-border bg-soc-bg hover:border-soc-cyan px-4 py-2 text-xs font-semibold text-soc-textPrimary transition-all"
          >
            Return to SOC Console
          </button>
        </div>
      </div>
    );
  }

  const actionStr = typeof event.action === 'object' ? event.action.action : event.action;
  const isHighRisk = event.risk_score >= 66 || actionStr === "HARD_BLOCK";
  const isMediumRisk = event.risk_score >= 31 && event.risk_score <= 65;

  return (
    <div className="p-8 pb-16 min-h-screen">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-soc-border pb-6 mb-8">
        <div className="flex items-center gap-4">
          <Link
            href="/dashboard"
            className="flex h-9 w-9 items-center justify-center rounded border border-soc-border bg-soc-surface text-soc-textSecondary hover:border-soc-cyan hover:text-soc-cyan transition-all"
          >
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="font-mono text-[10px] text-soc-textSecondary uppercase tracking-widest font-semibold">
                INCIDENT INVESTIGATION FILE
              </span>
            </div>
            <h1 className="font-display text-2xl font-extrabold tracking-tight text-soc-textPrimary flex items-center gap-2">
              <FileText className="h-6 w-6 text-soc-cyan" />
              Case: {event.entity_id}
            </h1>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={downloadCaseReport}
            className="flex items-center justify-center gap-2 rounded border border-soc-border bg-soc-surface hover:border-soc-cyan text-soc-textSecondary hover:text-soc-cyan px-4 py-2.5 text-xs font-semibold uppercase tracking-wider transition-all"
          >
            <Download className="h-4 w-4" />
            DOWNLOAD CASE SUMMARY
          </button>
          
          <button
            onClick={() => api.downloadCasePdf(event.id)}
            className="flex items-center justify-center gap-2 rounded border border-soc-cyan bg-soc-cyan/10 hover:bg-soc-cyan hover:text-soc-bg px-4 py-2.5 text-xs font-semibold uppercase tracking-wider text-soc-cyan transition-all"
          >
            <FileDown className="h-4 w-4" />
            DOWNLOAD CASE PDF
          </button>
        </div>
      </div>

      {/* Main Core Columns */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Side: Summary & Explanation & SHAP (55%) */}
        <div className="lg:col-span-6 flex flex-col gap-8">
          {/* Risk Header Block */}
          <div className="rounded-lg border border-soc-border bg-soc-surface p-6 flex items-center justify-between gap-6">
            <div className="flex items-center gap-6">
              <RiskScoreRing score={event.risk_score} size={110} strokeWidth={8} />
              <div>
                <h3 className="font-display text-sm font-bold text-soc-textSecondary uppercase tracking-wider mb-1">
                  Threat Probability
                </h3>
                <div className="font-mono text-3xl font-bold text-soc-textPrimary mb-1 flex items-center gap-2">
                  {event.risk_score.toFixed(2)}%
                  {event.confidence && (
                    <span
                      title={event.confidence.reasoning}
                      className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full border text-[10px] font-mono font-bold cursor-help"
                      style={{
                        borderColor: event.confidence.confidence_label === 'HIGH' ? '#00D4FF'
                                   : event.confidence.confidence_label === 'MEDIUM' ? '#FFB800'
                                   : '#FF3B5C',
                        color: event.confidence.confidence_label === 'HIGH' ? '#00D4FF'
                             : event.confidence.confidence_label === 'MEDIUM' ? '#FFB800'
                             : '#FF3B5C'
                      }}
                    >
                      {event.confidence.confidence_label} ({event.confidence.confidence_pct}%)
                    </span>
                  )}
                </div>
                <div className="text-[10px] text-soc-textSecondary font-mono uppercase">
                  Logged: {new Date(event.timestamp).toLocaleString("en-IN")}
                </div>
              </div>
            </div>

            {/* Friction level indicator badge */}
            <div className="text-right">
              <span className="text-[10px] text-soc-textSecondary font-bold block mb-1">DECISION LEVEL</span>
              <span className={`inline-block rounded px-3 py-1 font-bold text-xs uppercase tracking-widest border ${
                isHighRisk 
                  ? "bg-soc-red/10 text-soc-red border-soc-red/30" 
                  : isMediumRisk 
                  ? "bg-soc-amber/10 text-soc-amber border-soc-amber/30" 
                  : "bg-soc-green/10 text-soc-green border-soc-green/30"
              }`}>
                {event.action ? (typeof event.action === 'object' ? (event.action as any).action.replace(/_/g, " ") : event.action.replace(/_/g, " ")) : "SILENT_PASS"}
              </span>
            </div>
          </div>

          {/* Compliance Explanation blockquote */}
          <div className="rounded-lg border-l-4 border-soc-cyan bg-soc-surface p-6">
            <h3 className="font-display text-xs font-bold uppercase tracking-wider text-soc-cyan mb-3 flex items-center gap-1.5">
              <Cpu className="h-4 w-4" />
              AI Compliance Analysis ({event.provider_used === "template" ? "Offline" : "LLM"})
            </h3>
            <blockquote className="italic">
              <TypewriterText text={event.explanation} speed={10} />
            </blockquote>
          </div>

          {/* SHAP Chart */}
          <div className="rounded-lg border border-soc-border bg-soc-surface p-6">
            <h3 className="font-display text-sm font-bold uppercase tracking-wider text-soc-textPrimary mb-4">
              SHAP attribution contributions
            </h3>
            <ShapBarChart attributions={event.shap_attributions} />
          </div>
        </div>

        {/* Right Side: Node Link Graph Visualization (45%) */}
        <div className="lg:col-span-6 flex flex-col gap-6">
          <div className="border-b border-soc-border pb-3">
            <h2 className="font-display text-lg font-bold text-soc-textPrimary uppercase tracking-wider flex items-center gap-2">
              <Layers className="h-5 w-5 text-soc-cyan" />
              Incident graph visualization (2-Hop Neighborhood)
            </h2>
          </div>

          {/* Graph canvas container */}
          {graphLoading ? (
            <div className="flex h-[400px] w-full items-center justify-center rounded-lg border border-soc-border bg-soc-surface/40 text-soc-cyan">
              <span className="h-8 w-8 animate-spin rounded-full border-2 border-soc-cyan border-t-transparent"></span>
            </div>
          ) : subgraph ? (
            <div className="flex flex-col gap-4">
              <GraphCanvas
                nodes={subgraph.nodes}
                edges={subgraph.edges}
                onNodeSelect={(node) => setSelectedNode(node)}
                height={400}
                highlightNeighbors={true}
              />

              {/* Node Inspector Side Panel / Lower Block */}
              {selectedNode ? (
                <div className="rounded-lg border border-soc-border bg-soc-surface p-5">
                  <div className="flex items-center justify-between border-b border-soc-border/60 pb-3 mb-3">
                    <h4 className="font-display text-xs font-bold uppercase tracking-wider text-soc-cyan">
                      Node Properties Inspector
                    </h4>
                    <span className="font-mono text-[10px] text-soc-textSecondary uppercase">
                      [{selectedNode.type}]
                    </span>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-3 max-h-48 overflow-y-auto pr-2">
                    {Object.entries(selectedNode.properties).map(([key, val]: any) => (
                      <div key={key} className="border-b border-soc-border/20 pb-1.5 text-xs">
                        <span className="text-soc-textSecondary block font-semibold mb-0.5">{key}</span>
                        <span className="font-mono text-soc-textPrimary break-all">
                          {typeof val === "boolean" ? (val ? "TRUE" : "FALSE") : val.toString()}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <div className="rounded-lg border border-dashed border-soc-border bg-soc-surface/40 p-4 text-center text-xs text-soc-textSecondary">
                  Click on any node in the graph to inspect its database attributes.
                </div>
              )}
            </div>
          ) : (
            <div className="rounded-lg border border-dashed border-soc-border bg-soc-surface/40 p-12 text-center text-xs text-soc-textSecondary">
              Failed to connect or fetch graph visualization for this entity. Check Neo4j status.
            </div>
          )}

          {/* Audit Trail Monospace Code Block */}
          <div className="rounded-lg border border-soc-border bg-soc-surface p-6">
            <h3 className="font-display text-xs font-bold uppercase tracking-wider text-soc-textSecondary mb-3 flex items-center gap-1.5">
              <Database className="h-4 w-4" />
              Audit Log Payload JSON
            </h3>
            <pre className="font-mono text-[10px] bg-soc-bg rounded p-4 text-soc-textPrimary border border-soc-border overflow-x-auto max-h-48">
              {JSON.stringify(event, null, 2)}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
